---
# This Github workflow will run jobs to build java-app.
name: spring-petclinic
#test
on:
  push:
  workflow_dispatch:
permissions:
  pull-requests: write

jobs:
  ci-package-application:
    name: Package Application
    runs-on: [ubuntu-latest]
    steps:

      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Maven Package
        run: mvn --batch-mode --update-snapshots package

  ci-create-container-image:
    name: Create Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: spring-petclinic # TODO: hard coded
          tags: ${{ github.sha }}
          containerfiles: |
            ./Containerfile

      #- name: ci-create-container-image
      #  run: psr --help

      #- name: ci-push-container-image-to-repository
      #  run: psr --help

