---
# This Github workflow will run jobs to build java-app.
name: spring-petclinic
on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
permissions:
  pull-requests: write

jobs:
  ci-package-application:
    name: Package Application
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Maven Package
        run: mvn --batch-mode --update-snapshots package

      - uses: actions/upload-artifact@v1
        with:
          name: maven-output
          path: target/
          

  ci-create-container-image:
    name: Create Container Image
    needs: ci-package-application
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v1
        with:
          name: maven-output
          path: target/

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: spring-petclinic # TODO: hard coded
          tags: ${{ github.sha }}
          containerfiles: |
            ./Containerfile

  ci-push-container-image-to-repository:
    name: Push Container Image to Repository
    needs: ci-create-container-image
    runs-on: ubuntu-latest
    steps:
      - uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.ci-create-container-image.outputs.image }}
          tags: ${{ steps.ci-create-container-image.outputs.tags }}
          registry: quay.io/dwinchell_redhat
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      #- name: ci-create-container-image
      #  run: psr --help

      #- name: ci-push-container-image-to-repository
      #  run: psr --help

