---
# This Github workflow will run jobs to build java-app.
name: spring-petclinic
#test
on:
  push:
  workflow_dispatch:
permissions:
  pull-requests: write

jobs:
  continuous-integration:
    runs-on: [ubuntu-latest]
    steps:

      - name: setup-app-clone
        uses: actions/checkout@v3

      #- name: ci-generate-metadata
      #  run: psr -s generate-metadata -c ${{ inputs.stepRunnerConfigDir }}/psr.yaml

      - name: ci-package-application
        run: psr -s package -c ${{ inputs.stepRunnerConfigDir }}/psr.yaml

      - name: ci-create-container-image
        run: psr --help

      - name: ci-push-container-image-to-repository
        run: psr --help

